import {
  LayoutDashboard,
  Building2,
  ShieldCheck,
  Users,
  FolderKanban,
  UsersRound,
  Activity,
  BarChart3,
  ServerCog,
  Settings,
  ListChecks,
  CreditCard,
  Coins,
  Receipt,
  FileCheck2,
  CalendarClock,
  CalendarDays,
  Trophy,
  IdCard,
} from "lucide-react";
import type { NavItem } from "@/components/layout/nav-config";

export const ADMIN_NAV: NavItem[] = [
  { label: "Command Center", href: "/admin", icon: LayoutDashboard },
  { label: "Organization", href: "/admin/organization", icon: Building2 },
  { label: "Users", href: "/admin/users", icon: Users },
  { label: "Teams", href: "/admin/teams", icon: UsersRound },
  { label: "Projects", href: "/admin/projects", icon: FolderKanban },
  { label: "Tasks", href: "/admin/tasks", icon: ListChecks },
  { label: "Work Verification", href: "/admin/work-verification", icon: FileCheck2 },
  { label: "Credits", href: "/admin/credits", icon: Coins },
  { label: "Meetings", href: "/meetings", icon: CalendarClock },
  { label: "Calendar", href: "/calendar", icon: CalendarDays },
  { label: "Leaderboard", href: "/leaderboard", icon: Trophy },
  { label: "Billing", href: "/admin/billing", icon: CreditCard },
  { label: "Analytics", href: "/admin/analytics", icon: BarChart3 },
  { label: "Activity", href: "/admin/activity", icon: Activity },
  { label: "Profile", href: "/profile", icon: IdCard },
  { label: "Settings", href: "/admin/settings", icon: Settings },
];

export const SUPER_ADMIN_NAV: NavItem[] = [
  { label: "Command Center", href: "/superadmin", icon: LayoutDashboard },
  { label: "Organizations", href: "/superadmin/organizations", icon: Building2 },
  { label: "Administrators", href: "/superadmin/admins", icon: ShieldCheck },
  { label: "Users", href: "/superadmin/users", icon: Users },
  { label: "Projects", href: "/superadmin/projects", icon: FolderKanban },
  { label: "Teams", href: "/superadmin/teams", icon: UsersRound },
  { label: "Subscriptions", href: "/superadmin/subscriptions", icon: Receipt },
  { label: "Activity", href: "/superadmin/activity", icon: Activity },
  { label: "Analytics", href: "/superadmin/analytics", icon: BarChart3 },
  { label: "System", href: "/superadmin/system", icon: ServerCog },
  { label: "Profile", href: "/profile", icon: IdCard },
  { label: "Settings", href: "/superadmin/settings", icon: Settings },
];
